# Matrix Operations
Let A is a $m \times n$ matrix, $B \in R^3$ a scalar.

$Ax=b \Longrightarrow x = A^{-1}b$

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,3,2], [3,2,1], [4,1,2]])
A

matrix([[1, 3, 2],
        [3, 2, 1],
        [4, 1, 2]])

In [3]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[-0.23076923,  0.30769231,  0.07692308],
        [ 0.15384615,  0.46153846, -0.38461538],
        [ 0.38461538, -0.84615385,  0.53846154]])

In [4]:
b = np.matrix([8,7,9]).transpose()
b

matrix([[8],
        [7],
        [9]])

In [5]:
x = np.dot(A_inv,b)
x

matrix([[1.],
        [1.],
        [2.]])

## Eigenvalues and Eigenvectors

An eigenvector of a square matrix A is a non-zero vector $\vec{v}$ such that multiplication by A alters only the scale of $\vec{v}$:

$Av = \lambda v$

In [6]:
# obtain 𝜆 and 𝑣
scalar_lambda, vector_v = np.linalg.eig(A)
scalar_lambda, vector_v

(array([ 6.26496597, -2.20571722,  0.94075125]),
 matrix([[ 0.54912336,  0.7156141 , -0.08186527],
         [ 0.53650412, -0.36951906, -0.55171846],
         [ 0.64080173, -0.59274963,  0.8300029 ]]))

In [12]:
# print 𝑣_1
vector_v[:,0]

matrix([[0.54912336],
        [0.53650412],
        [0.64080173]])

In [13]:
# obtain A * 𝑣_1
A_vector_v = A * vector_v[:,0]
A_vector_v

matrix([[3.44023919],
        [3.36118007],
        [4.01460104]])

In [9]:
# print 𝜆_1
scalar_lambda[0]

6.26496597299326

In [14]:
# obtain 𝜆_1 * 𝑣_1
evalue_evect = scalar_lambda[0] * vector_v[:,0]
evalue_evect

matrix([[3.44023919],
        [3.36118007],
        [4.01460104]])